# Generated by Django 5.2.9 on 2026-08-01 14:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja_web', '0011_acompanhamento_empresa_categoria_empresa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('empresa_nome', models.CharField(blank=True, max_length=150)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_usuarios', models.PositiveIntegerField(default=1)),
                ('limite_empresas', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['valor_mensal', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('ativa', 'Ativa'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada'), ('suspensa', 'Suspensa')], default='trial', max_length=20)),
                ('gateway', models.CharField(blank=True, max_length=40)),
                ('gateway_customer_id', models.CharField(blank=True, max_length=120)),
                ('gateway_subscription_id', models.CharField(blank=True, max_length=120)),
                ('inicio_ciclo', models.DateField(default=django.utils.timezone.localdate)),
                ('fim_ciclo', models.DateField(blank=True, null=True)),
                ('trial_ate', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='loja_web.empresa')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_responsavel', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='billing.plano')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
