# Generated by Django 5.2.9 on 2026-08-13 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='plano',
            name='sistema',
            field=models.ForeignKey(blank=True, help_text='Deixe em branco para disponibilizar este plano para todos os sistemas.',
                                    null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='billing.sistema'),
        ),
    ]
