"""
Django settings for loja_app project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 't', 'yes', 'y', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY', 'django-insecure--r&egz*)nhz!tgrn6=x#jz!3jevjen(1!qqqih*&a^+s=4y1-%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = [host.strip() for host in os.getenv(
    'DJANGO_ALLOWED_HOSTS', '*').split(',') if host.strip()]

# Handlers de erro
handler403 = 'loja_web.views.custom_403_view'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'site_publico',
    'billing',
    'loja_web',
    'django.forms',
    'widget_tweaks',
    'rest_framework',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'loja_web.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'loja_app.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'loja_web.context_processors.empresa',
                'loja_web.context_processors.version_context',


            ],
            'libraries': {
                'pedido_filters': 'loja_web.templatetags.pedido_filters',

            },
        },
    },
]

# Ultima atualização da versão: 25/10/2025 as 23:17
VERSION = '26.07.15'

# Integracao com Evolution API (WhatsApp)
EVOLUTION_ENABLED = env_bool('EVOLUTION_ENABLED', False)
EVOLUTION_BASE_URL = os.getenv(
    'EVOLUTION_API_URL',
    os.getenv('EVOLUTION_BASE_URL', 'http://localhost:8080'),
).rstrip('/')
EVOLUTION_API_KEY = os.getenv('EVOLUTION_API_KEY', '').strip()
EVOLUTION_INSTANCE = os.getenv(
    'EVOLUTION_API_INSTANCE',
    os.getenv('EVOLUTION_INSTANCE', 'loja'),
).strip()
EVOLUTION_SEND_TEXT_PATH = os.getenv(
    'EVOLUTION_SEND_TEXT_PATH', '/message/sendText/{instance}').strip()
EVOLUTION_WEBHOOK_SECRET = os.getenv('EVOLUTION_WEBHOOK_SECRET', '').strip()

WSGI_APPLICATION = 'loja_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'BD/systemdb.sqlite3',
#        #'NAME': BASE_DIR / 'systemdb.sqlite3',
#    }
# }


# Banco configurável por ambiente para facilitar deploy no mesmo host de outros sistemas.
DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').strip().lower()

if DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'sistema'),
            'USER': os.getenv('DB_USER', 'sistema2'),
            'PASSWORD': os.getenv('DB_PASSWORD', '123456'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
elif DB_ENGINE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', 'systembd'),
            'USER': os.getenv('DB_USER', 'system_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', '123456'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '3306'),
        }
    }
elif DB_ENGINE == 'mssql':
    DATABASES = {
        'default': {
            'ENGINE': 'mssql',
            'NAME': os.getenv('DB_NAME', 'LojaDB'),
            'HOST': os.getenv('DB_HOST', 'DESKTOP-NTN\\SQLEXPRESS'),
            'OPTIONS': {
                'driver': os.getenv('DB_DRIVER', 'ODBC Driver 17 for SQL Server'),
                'trusted_connection': os.getenv('DB_TRUSTED_CONNECTION', 'yes'),
                'TrustServerCertificate': os.getenv('DB_TRUST_SERVER_CERTIFICATE', 'yes'),
                'unicode_results': True,
                'extra_params': os.getenv('DB_EXTRA_PARAMS', 'charset=utf8'),
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.getenv('SQLITE_PATH', 'BD/systemdb.sqlite3'),
        }
    }

# DATABASES = {
#     'default': {
#         'ENGINE': 'mssql',
#         'NAME': 'LojaDB',
#         'HOST': 'DESKTOP-NTN\\SQLEXPRESS',
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',
#             'trusted_connection': 'yes',  # se usar autenticação Windows
#             'TrustServerCertificate': 'yes',
#             'unicode_results': True,   # importantíssimo
#             'extra_params': 'charset=utf8',
#         },
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'systembd',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = False

DECIMAL_SEPARATOR = ','
USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = '.'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

WHITENOISE_USE_FINDERS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Redirecionamentos de autenticação
LOGIN_URL = 'login'                # Para onde vai quem tenta acessar sem estar logado
LOGIN_REDIRECT_URL = 'home'        # Para onde vai depois de logar com sucesso
LOGOUT_REDIRECT_URL = 'login'      # Para onde vai depois de sair


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    'site_title': 'SGP',

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    'site_header': 'SGP',

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    'site_brand': 'SGP',

    'icons': {
        'auth': 'fas fa-users-cog',
        'auth.user': 'fas fa-user',
        'auth.Group': 'fas fa-users',
        'loja_web.CondicaoPagamento': 'fa-solid fa-money-bill-1-wave',
        'loja_web.categoria': 'fas fa-object-group',
        'loja_web.produto': 'fas fa-box',
        'loja_web.pedido': 'fas fa-shopping-cart',
        'loja_web.pedidoitem': 'fas fa-cart-plus',
        'loja_web.cliente': 'fa-duotone fa-solid fa-address-book',
        'loja_web.fornecedor': 'fas fa-store',
        'loja_web.servicos': 'fa-solid fa-briefcase',
        'loja_web.entradaestoque': 'fa-duotone fa-solid fa-dolly',
        'loja_web.movimentofinanceiro': 'fa-solid fa-money-check-dollar',
        'loja_web.fechamentocaixa': 'fa-solid fa-cash-register',
        'loja_web.venda': 'fa-solid fa-cash-register',
        'loja_web.itemvenda': 'fa-solid fa-cash-register',
        'loja_web.itenspedido': 'fa-solid fa-cash-register',
        'loja_web.itemservico': 'fa-solid fa-cash-register',
        'loja_web.permissaopersonalizada': 'fa-solid fa-user-shield',
    },

    # Welcome text on the login screen
    'welcome_sign': 'Bem-vindo(a) ao SGP',

    # Copyright on the footer
    'copyright': 'InovaCore LTDA',

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string
    'search_model': ['loja_web.Produto',],

    # Whether to show the UI customizer on the sidebar
    'show_ui_builder': True,
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "simplex",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


_LOGS_DIR = BASE_DIR / 'logs'
_LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
        'verbose': {
            'format': '[{asctime}] {levelname} {name} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_errors': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'licenca': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'loja_web': {
            'handlers': ['console', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}
