# Generated by Django 5.0.14 on 2025-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
