# Generated by Django 5.2.1 on 2026-01-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='total_entradas',
        ),
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='total_saidas',
        ),
        migrations.RemoveField(
            model_name='fechamentocaixa',
            name='total_vendas',
        ),
    ]
