# Generated by Django 5.2.1 on 2026-01-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0002_remove_fechamentocaixa_total_entradas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='chave_licenca',
            field=models.CharField(blank=True, help_text='Chave UUID ou string fornecida ao cliente', max_length=255, null=True, verbose_name='Chave de Licença'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cliente_id',
            field=models.CharField(blank=True, help_text='ID usado no app para validar a licença', max_length=50, null=True, verbose_name='ID do Cliente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='server_url',
            field=models.URLField(blank=True, help_text='Ex: http://127.0.0.1:8000/api/verificar_licenca', max_length=255, null=True, verbose_name='URL do Servidor de Licença'),
        ),
    ]
