# Generated by Django 5.0.14 on 2025-05-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0002_alter_produto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
