# Generated by Django 5.0.14 on 2025-05-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0003_produto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
