# Generated by Django 5.2.9 on 2026-03-25 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0003_empresa_chave_licenca_empresa_cliente_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('criar', 'Criar'), ('editar', 'Editar'), ('excluir', 'Excluir'), ('venda', 'Venda'), ('estoque', 'Estoque'), ('financeiro', 'Financeiro'), ('caixa', 'Caixa'), ('pedido', 'Pedido'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('entidade', models.CharField(blank=True, max_length=100)),
                ('detalhes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
