# Generated by Django 5.2.9 on 2026-03-26 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0005_empresa_segmento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acompanhamento',
                'verbose_name_plural': 'Acompanhamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo (kg)'), ('lt', 'Litro (lt)')], default='un', max_length=2, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ItensPedidoAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(default=1)),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja_web.acompanhamento')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='loja_web.itenspedido')),
            ],
            options={
                'verbose_name': 'Acompanhamento do Item',
                'verbose_name_plural': 'Acompanhamentos do Item',
            },
        ),
    ]
