# Generated by Django 5.2.9 on 2026-03-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0006_acompanhamento_produto_unidade_medida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_em_receitas', to='loja_web.produto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='loja_web.produto')),
            ],
            options={
                'verbose_name': 'Componente do Produto',
                'verbose_name_plural': 'Componentes do Produto',
                'unique_together': {('produto', 'ingrediente')},
            },
        ),
    ]
