# Generated by Django 5.2.1 on 2026-03-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0007_produtocomposicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Baixada')),
                ('motivo', models.CharField(blank=True, max_length=150, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data da Baixa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas_estoque', to='loja_web.produto')),
            ],
            options={
                'verbose_name': 'Baixa de Estoque',
                'verbose_name_plural': 'Baixas de Estoque',
                'ordering': ['-data_saida'],
            },
        ),
    ]
