# Generated by Django 5.2.9 on 2026-03-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0008_saidaestoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade Recebida'),
        ),
    ]
