# Generated by Django 5.2.9 on 2026-09-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0011_acompanhamento_empresa_categoria_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissaosistema',
            options={'permissions': [('acessar_dashboard', 'Pode acessar o dashboard'), ('gerenciar_usuarios', 'Pode gerenciar usuários'), ('cadastrar_produto', 'Pode cadastrar produto'), ('ver_relatorios', 'Pode ver relatórios'), ('editar_config', 'Pode editar configurações'), ('realizar_venda', 'Pode realizar venda direta'), ('ver_clientes', 'Pode ver clientes'), ('gerenciar_fornecedores', 'Pode gerenciar fornecedores'), ('criar_produto', 'Pode criar produto'), ('gerenciar_estoque', 'Pode gerenciar estoque'), ('ver_pedidos', 'Pode ver pedidos/OS'), ('criar_pedido', 'Pode criar pedido/OS'), ('encerrar_pedido', 'Pode encerrar pedido/OS'), ('gerenciar_pedidos', 'Pode gerenciar pedidos/OS'), ('gerenciar_pedidos_compras', 'Pode gerenciar pedidos de compras'), ('gerenciar_financeiro', 'Pode gerenciar financeiro'), ('fechamento_caixa', 'Pode fazer fechamento de caixa'), ('gerenciar_servicos', 'Pode gerenciar serviços'), ('gerenciar_categorias', 'Pode gerenciar categorias'), ('gerenciar_condicoes_pagamento', 'Pode gerenciar condições de pagamento'), ('ver_condicoes_pagamento', 'Pode ver condições de pagamento'), ('criar_condicao_pagamento', 'Pode criar condição de pagamento'), ('gerenciar_cobranca_whatsapp', 'Pode gerenciar regras de cobrança via WhatsApp'), ('ver_cobranca_whatsapp', 'Pode ver cobranças via WhatsApp')], 'verbose_name': 'Permissão do Sistema', 'verbose_name_plural': 'Permissões do Sistema'},
        ),
        migrations.CreateModel(
            name='RegraCobrancaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da regra')),
                ('aplicar_a', models.CharField(choices=[('todos', 'Pedidos e Serviços'), ('produtos', 'Somente Pedidos (produtos)'), ('servicos', 'Somente Serviços')], default='todos', max_length=10, verbose_name='Aplicar a')),
                ('dias_referencia', models.IntegerField(default=1, help_text='Negativo = dias antes do vencimento. 0 = no dia do vencimento. Positivo = dias após o vencimento (atraso).', verbose_name='Disparar (dias)')),
                ('repetir_a_cada_dias', models.PositiveIntegerField(default=0, help_text='Deixe 0 para enviar apenas uma vez. Ex: 5 = reenvia a cada 5 dias enquanto estiver em aberto.', verbose_name='Repetir a cada (dias)')),
                ('mensagem', models.TextField(default='Olá {cliente}, tudo bem? Identificamos uma pendência no valor de R$ {valor} com vencimento em {vencimento} referente ao pedido {pedido}. Qualquer dúvida estamos à disposição.', help_text='Placeholders disponíveis: {cliente}, {valor}, {vencimento}, {pedido}, {empresa}', verbose_name='Mensagem')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_cobranca_whatsapp', to='loja_web.empresa')),
            ],
            options={
                'verbose_name': 'Regra de Cobrança WhatsApp',
                'verbose_name_plural': 'Regras de Cobrança WhatsApp',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EnvioCobrancaWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_destino', models.CharField(blank=True, max_length=30)),
                ('mensagem_enviada', models.TextField(blank=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('resposta_api', models.TextField(blank=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_cobranca_whatsapp', to='loja_web.empresa')),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_cobranca_whatsapp', to='loja_web.movimentofinanceiro')),
                ('regra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='loja_web.regracobrancawhatsapp')),
            ],
            options={
                'verbose_name': 'Envio de Cobrança WhatsApp',
                'verbose_name_plural': 'Envios de Cobrança WhatsApp',
                'ordering': ['-data_envio'],
            },
        ),
    ]
