# Generated by Django 5.2.9 on 2026-09-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_web', '0012_alter_permissaosistema_options_regracobrancawhatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regracobrancawhatsapp',
            name='mensagem',
            field=models.TextField(default='Qualquer dúvida sobre este lançamento, estamos à disposição. Empresa: {empresa}.', help_text='A cobrança já inclui os dados do financeiro. Use como complemento. Placeholders: {cliente}, {valor}, {vencimento}, {pedido}, {empresa}, {descricao}, {parcela}, {total_parcelas}, {status}, {observacao}', verbose_name='Mensagem'),
        ),
    ]
